// Regenerates model.js by lifting the pure functions out of index.html.
// Re-run whenever a signature changes. No DOM, no rendering, no page globals.
const fs = require('fs');
const path = require('path');

const INDEX = process.argv[2] || 'C:/Users/markf/xc-analysis/index.html';
const OUTDIR = process.argv[3] || __dirname;

const html = fs.readFileSync(INDEX, 'utf8');
// the app lives in the largest <script> that is not the seed data block
const blocks = [...html.matchAll(/<script(?![^>]*id="seed")[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);
const src = blocks.sort((a, b) => b.length - a.length)[0];
const lines = src.split(/\r?\n/);

// Names to lift. Order matters only for readability; JS hoists functions.
const WANT = [
  'CLASSES', 'CLS', 'LEAGUES', 'AUTO', 'autoFor', 'autoTotal', 'TEAM_LEAGUE', 'setClass',
  'CAL', 'MARK_W', 'LONE', 'TEAM_SHARE', 'SIG_T',
  // buildModel reads this, so the headless copy needs it declared or it throws
  // the moment the function runs rather than when the file loads
  'NEXT_SEASON',
  'splitCSVLine', 'toSeconds', 'fmt', 'parseCSV', 'buildModel', 'scoreMeet',
  'SK_HI', 'SK_MEAN', 'SK_SD',
  'playDistricts', 'playState', 'skew', 'spare', 'gauss', 'pickMark', 'draw', 'shift',
  'oneSeason', 'blankTally', 'runnerTally',
];

// Find a top-level declaration by name and return its full text, brace-balanced.
function grab(name) {
  const heads = ['function ' + name + '(', 'const ' + name + '=', 'const ' + name + ' =',
                 'let ' + name + '=', 'let ' + name + ' ='];
  let start = -1, isFn = false;
  for (let i = 0; i < lines.length && start < 0; i++) {
    for (const h of heads) {
      if (lines[i].startsWith(h)) { start = i; isFn = h.startsWith('function'); break; }
    }
  }
  if (start < 0) return null;

  let depth = 0, seen = false, out = [];
  for (let i = start; i < lines.length; i++) {
    const line = lines[i];
    out.push(line);
    for (const ch of line) {
      if (ch === '{' || ch === '(' || ch === '[') { depth++; seen = true; }
      else if (ch === '}' || ch === ')' || ch === ']') depth--;
    }
    if (depth !== 0) continue;
    if (isFn) {
      // a function ends at its balanced closing brace
      if (seen) return out.join('\n');
    } else {
      // a const/let ends at its semicolon, which may carry a trailing comment
      if (/;\s*(\/\/.*)?$/.test(line.trimEnd())) return out.join('\n');
    }
  }
  return null;
}

const parts = [], missing = [];
for (const n of WANT) {
  const s = grab(n);
  if (s) parts.push(s); else missing.push(n);
}

// AUTO_PER / AT_LARGE / FIELD must be mutable so a backtest can model a
// different season's berth allocation (2025 ran 14 + 4, 2026 runs 14 + 2).
for (let i = 0; i < parts.length; i++) {
  parts[i] = parts[i].replace(/^const FIELD=/m, 'let FIELD=');
}

parts.push('let DATA=[];');
// a freshly required module should be usable without ceremony
parts.push('try{ setClass("6A","M"); }catch(e){}');

parts.push(`module.exports = {
  get LEAGUES(){return LEAGUES;}, get LG(){return LG;}, get TEAM_LEAGUE(){return TEAM_LEAGUE;},
  get AUTO(){return AUTO;}, get CLS(){return CLS;}, setCLS(c){ CLS=c; },
  setClass, get AT_LARGE(){return AT_LARGE;}, get FIELD(){return FIELD;},
  get SC(){return SC;}, get PL(){return PL;},
  CAL, MARK_W, TEAM_SHARE, SIG_T, SIG_I,
  parseCSV, toSeconds, fmt, buildModel, scoreMeet, playDistricts, playState,
  gauss, skew, pickMark, draw, shift, oneSeason, blankTally, runnerTally,
  get IND(){return IND;}, setInd(n){ IND=n; },
  get DATA(){return DATA;},
  setDATA(d){ DATA = d; },
  setLeagues(L){
    LEAGUES = L;
    LG = Object.keys(LEAGUES);
    for(const k in TEAM_LEAGUE) delete TEAM_LEAGUE[k];
    for(const [lg,ts] of Object.entries(LEAGUES)) ts.forEach(x=>TEAM_LEAGUE[x]=lg);
    FIELD = autoTotal() + AT_LARGE;
  },
  setBerths(auto, atLarge){
    AUTO = {};
    if (typeof auto === 'number') LG.forEach(l => AUTO[l] = auto); else Object.assign(AUTO, auto);
    AT_LARGE = atLarge; FIELD = autoTotal() + AT_LARGE;
  },
  setDepths(score, place){ SC = score; PL = place || 7; },
};`);

const js = '// GENERATED by extract_model.js from index.html - do not edit by hand\n\n'
         + parts.join('\n\n') + '\n';
fs.writeFileSync(path.join(OUTDIR, 'model.js'), js);
console.log('extracted ' + (WANT.length - missing.length) + ' of ' + WANT.length + ' declarations');
if (missing.length) console.log('MISSING: ' + missing.join(', '));
console.log('wrote ' + path.join(OUTDIR, 'model.js') + ' (' + js.length + ' bytes)');

// Smoke the result now. A constant left behind in index.html only shows up when
// the function that uses it runs, which is otherwise a long way downstream.
try {
  const m = require(path.join(OUTDIR, 'model.js'));
  m.gauss(); m.skew();
  m.pickMark({ marks: [100, 110], w: [0.4, 0.6] });
  m.scoreMeet([{ idx: 0, rIdx: [0, 1, 2, 3, 4] }], [1, 2, 3, 4, 5]);
  m.setDATA(Array.from({ length: 6 }, (_, i) =>
    ({ g: 'M', name: 'R' + i, team: 'T', dist: 5000, sb: 900 + i * 10, grade: '12', cls: '6A' })));
  m.setLeagues({ L1: ['T'] });
  m.buildModel('M', 5000);
  console.log('smoke test ok');
} catch (e) {
  console.log('SMOKE TEST FAILED: ' + e.message);
  console.log('  add the missing declaration to WANT and regenerate.');
  process.exit(1);
}
