// GENERATED by extract_model.js from index.html - do not edit by hand

const CLASSES={
 "6A":{
  ab:{"Portland Interscholastic League":"PIL","Metro League":"Metro","Pacific Conference":"Pacific","Mt. Hood Conference":"Mt. Hood","Three Rivers League":"Three Rivers","Central Valley Conference":"Central Valley","Special District 1":"SD1"},
  M:{atLarge:2,score:5,ind:14,
    auto:{"Portland Interscholastic League":2,"Metro League":2,"Pacific Conference":2,"Mt. Hood Conference":2,"Three Rivers League":2,"Central Valley Conference":2,"Special District 1":2},
    lg:{"Portland Interscholastic League":["Benson Tech","Cleveland","Franklin","Grant","Ida B. Wells","Jefferson-Portland","Lincoln","McDaniel","Roosevelt"],
      "Metro League":["Beaverton","Jesuit","Mountainside","Southridge","Sunset","Westview"],
      "Pacific Conference":["Century","Forest Grove","Glencoe","McMinnville","Newberg","Sherwood"],
      "Mt. Hood Conference":["Barlow","Central Catholic","Clackamas","David Douglas","Gresham","Adrienne Nelson","Reynolds"],
      "Three Rivers League":["Lake Oswego","Lakeridge","Oregon City","Tigard","Tualatin","West Linn"],
      "Central Valley Conference":["McKay","McNary","North Salem","South Salem","Sprague","West Salem"],
      "Special District 1":["Grants Pass","North Medford","Roseburg","Sheldon","South Eugene","South Medford"]}},
  F:{atLarge:2,score:5,ind:14,
    auto:{"Portland Interscholastic League":2,"Metro League":2,"Pacific Conference":2,"Mt. Hood Conference":2,"Three Rivers League":2,"Central Valley Conference":2,"Special District 1":2},
    lg:{"Portland Interscholastic League":["Benson Tech","Cleveland","Franklin","Grant","Ida B. Wells","Jefferson-Portland","Lincoln","McDaniel","Roosevelt"],
      "Metro League":["Beaverton","Jesuit","Mountainside","Southridge","Sunset","Westview"],
      "Pacific Conference":["Century","Forest Grove","Glencoe","McMinnville","Newberg","Sherwood"],
      "Mt. Hood Conference":["Barlow","Central Catholic","Clackamas","David Douglas","Gresham","Adrienne Nelson","Reynolds"],
      "Three Rivers League":["Lake Oswego","Lakeridge","Oregon City","St Mary's Academy","Tigard","Tualatin","West Linn"],
      "Central Valley Conference":["McKay","McNary","North Salem","South Salem","Sprague","West Salem"],
      "Special District 1":["Grants Pass","North Medford","Roseburg","Sheldon","South Eugene","South Medford"]}}},
 "5A":{
  ab:{"Northwest Oregon Conference":"NWOC","Greater Metro Conference":"Greater Metro","Mid-Willamette Conference":"Mid-Will","Intermountain Conference":"IMC","Special District 1":"SD1"},
  M:{atLarge:2,score:5,ind:7,
    auto:{"Northwest Oregon Conference":2,"Greater Metro Conference":2,"Mid-Willamette Conference":2,"Intermountain Conference":2,"Special District 1":2},
    lg:{"Northwest Oregon Conference":["Centennial","Hood River Valley","Milwaukie","Parkrose","Putnam","Sandy","St Helens"],
      "Greater Metro Conference":["Aloha","Canby","Hillsboro","La Salle Prep","Liberty","Wilsonville","Woodburn"],
      "Mid-Willamette Conference":["Corvallis","Crescent Valley","Dallas","Lebanon","Silverton","South Albany","West Albany"],
      "Intermountain Conference":["Bend","Caldera","Crook County","Mountain View","Redmond","Ridgeview","Summit"],
      "Special District 1":["Ashland","Churchill","Crater","Eagle Point","North Eugene","Springfield","Thurston","Willamette"]}},
  F:{atLarge:2,score:5,ind:7,
    auto:{"Northwest Oregon Conference":2,"Greater Metro Conference":2,"Mid-Willamette Conference":2,"Intermountain Conference":2,"Special District 1":2},
    lg:{"Northwest Oregon Conference":["Centennial","Hood River Valley","Milwaukie","Parkrose","Putnam","Sandy","St Helens"],
      "Greater Metro Conference":["Aloha","Canby","Hillsboro","La Salle Prep","Liberty","Wilsonville","Woodburn"],
      "Mid-Willamette Conference":["Corvallis","Crescent Valley","Dallas","Lebanon","Silverton","South Albany","West Albany"],
      "Intermountain Conference":["Bend","Caldera","Crook County","Mountain View","Redmond","Ridgeview","Summit"],
      "Special District 1":["Ashland","Churchill","Crater","Eagle Point","North Eugene","Springfield","Thurston","Willamette"]}}},
 "4A":{
  ab:{"Cowapa League":"Cowapa","Tri-Valley Conference":"Tri-Valley","Oregon West Conference":"Oregon West","Sky-Em League":"Sky-Em","Skyline Conference":"Skyline","Greater Oregon League":"Greater Oregon"},
  M:{atLarge:6,score:5,ind:7,
    auto:{"Cowapa League":1,"Tri-Valley Conference":1,"Oregon West Conference":1,"Sky-Em League":1,"Skyline Conference":1,"Greater Oregon League":1},
    lg:{"Cowapa League":["Astoria","Banks","Scappoose","Seaside","Tillamook","Valley Catholic"],
      "Tri-Valley Conference":["Estacada","Gladstone","Madras","Molalla","The Dalles"],
      "Oregon West Conference":["Cascade","Central","Newport","Philomath","Stayton","Taft"],
      "Sky-Em League":["Cottage Grove","Elmira","Junction City","Marist","Marshfield","North Bend","South Umpqua"],
      "Skyline Conference":["Cascade Christian","Henley","Hidden Valley","Klamath Union","Mazama","North Valley","Phoenix"],
      "Greater Oregon League":["Baker","La Grande","Ontario","Pendleton"]}},
  F:{atLarge:6,score:5,ind:7,
    auto:{"Cowapa League":1,"Tri-Valley Conference":1,"Oregon West Conference":1,"Sky-Em League":1,"Skyline Conference":1,"Greater Oregon League":1},
    lg:{"Cowapa League":["Astoria","Banks","Scappoose","Seaside","Tillamook","Valley Catholic"],
      "Tri-Valley Conference":["Estacada","Gladstone","Madras","Molalla","The Dalles"],
      "Oregon West Conference":["Cascade","Central","Newport","Philomath","Stayton","Taft"],
      "Sky-Em League":["Cottage Grove","Elmira","Junction City","Marist","Marshfield","North Bend","South Umpqua"],
      "Skyline Conference":["Cascade Christian","Henley","Hidden Valley","Klamath Union","Mazama","North Valley","Phoenix"],
      "Greater Oregon League":["Baker","La Grande","Ontario","Pendleton"]}}},
 "3A":{
  ab:{"Special District 1":"SD1","Special District 2":"SD2","Special District 3":"SD3","Special District 4":"SD4"},
  M:{atLarge:1,score:5,ind:7,
    auto:{"Special District 1":3,"Special District 2":3,"Special District 3":3,"Special District 4":2},
    lg:{"Special District 1":["Catlin Gabel","Corbett","Horizon Christian","Neah-Kah-Nie","Oregon Episcopal","Portland Adventist","Rainier","Riverdale","Warrenton","Westside Christian"],
      "Special District 2":["Amity","Blanchet Catholic","Dayton","Gervais","Harrisburg","Jefferson","Salem Academy","Santiam Christian","Scio","Willamina","Yamhill-Carlton"],
      "Special District 3":["Brookings-Harbor","Coquille","Creswell","Douglas","Glide","Illinois Valley","La Pine","Pleasant Hill","Sisters","Siuslaw","St Mary's","Sutherlin","Sweet Home","Trinity Lutheran"],
      "Special District 4":["Burns","Enterprise","McLoughlin","Nyssa","Riverside","Umatilla","Vale"]}},
  F:{atLarge:1,score:4,ind:4,
    auto:{"Special District 1":2,"Special District 2":2,"Special District 3":2,"Special District 4":1},
    lg:{"Special District 1":["Catlin Gabel","Corbett","Horizon Christian","Neah-Kah-Nie","Oregon Episcopal","Portland Adventist","Rainier","Riverdale","Warrenton","Westside Christian"],
      "Special District 2":["Amity","Blanchet Catholic","Dayton","Gervais","Harrisburg","Jefferson","Salem Academy","Santiam Christian","Scio","Willamina","Yamhill-Carlton"],
      "Special District 3":["Brookings-Harbor","Coquille","Creswell","Douglas","Glide","Illinois Valley","La Pine","Pleasant Hill","Sisters","Siuslaw","St Mary's","Sutherlin","Sweet Home","Trinity Lutheran"],
      "Special District 4":["Burns","Enterprise","McLoughlin","Nyssa","Riverside","Umatilla","Vale"]}}},
 "2A/1A":{
  ab:{"Special District 1":"SD1","Special District 2":"SD2","Special District 3":"SD3","Special District 4":"SD4"},
  M:{atLarge:2,score:5,ind:7,
    auto:{"Special District 1":3,"Special District 2":4,"Special District 3":3,"Special District 4":3},
    lg:{"Special District 1":["Clatskanie","Columbia Christian","Country Christian","Faith Bible Christian","Knappa","Nestucca","North Clackamas Christian","Paideia Classical Christian","Portland Christian","Riverside-WLWV","Southwest Christian","St. Stephen's Academy","Trinity Academy","Valor Christian","Vernonia"],
      "Special District 2":["C.S. Lewis Academy","Central Linn","Crosshill Christian","Crow","Delphian","East Linn Christian","Eugene Christian","Jewell","Kennedy","Livingstone Adventist Acad.","Lowell","Mapleton","McKenzie","Northwest Christian","Oakridge","Oregon School for the Deaf","Perrydale","Regis","Santiam","St Paul","Toledo","Triangle Lake","Veritas","Western Christian"],
      "Special District 3":["Bandon","Camas Valley","Culver","Days Creek","Glendale","Gold Beach","Harvest Christian","Lakeview","Myrtle Point","New Hope Christian","North Douglas","North Lake","Oakland","Paisley","Reedsport","Trout Lake","Yoncalla"],
      "Special District 4":["Echo","Elgin","Four Rivers","Grant Union","Griswold","Heppner","Imbler","Nixyaawii Community","Pilot Rock","Pine Eagle","Sherman","Stanfield","Union","Weston-McEwen"]}},
  F:{atLarge:3,score:4,ind:4,
    auto:{"Special District 1":1,"Special District 2":2,"Special District 3":1,"Special District 4":1},
    lg:{"Special District 1":["Clatskanie","Columbia Christian","Faith Bible Christian","Gaston","Knappa","Nestucca","North Clackamas Christian","Paideia Classical Christian","Portland Christian","Riverside-WLWV","Southwest Christian","St. Stephen's Academy","Trinity Academy","Valor Christian","Vernonia"],
      "Special District 2":["C.S. Lewis Academy","Central Linn","Crosshill Christian","Crow","Delphian","East Linn Christian","Eugene Christian","Kennedy","Livingstone Adventist Acad.","Lowell","Mapleton","McKenzie","Oakridge","Oregon School for the Deaf","Regis","Santiam","St Paul","Toledo","Triangle Lake","Veritas","Western Christian"],
      "Special District 3":["Bandon","Camas Valley","Culver","Days Creek","Glendale","Gold Beach","Lakeview","Myrtle Point","North Douglas","North Lake","Oakland","Yoncalla"],
      "Special District 4":["Echo","Elgin","Four Rivers","Grant Union","Griswold","Heppner","Imbler","Nixyaawii Community","Pilot Rock","Pine Eagle","Sherman","Stanfield","Trout Lake","Union","Weston-McEwen"]}}},
};

let CLS="6A";

let LEAGUES={}, ABBR={}, LG=[];

let AUTO={}, AT_LARGE=2, SC=5, PL=7, FIELD=16, IND=14;

const autoFor = lg => (lg in AUTO ? AUTO[lg] : 2);

const autoTotal = () => LG.reduce((s, lg) => s + autoFor(lg), 0);

const TEAM_LEAGUE={};

function setClass(c,g){
  CLS=c;
  const K=CLASSES[c], cfg=K[g];
  LEAGUES=cfg.lg; ABBR=K.ab; LG=Object.keys(LEAGUES);
  AUTO=cfg.auto; AT_LARGE=cfg.atLarge; SC=cfg.score; PL=7; IND=cfg.ind;
  FIELD=autoTotal()+AT_LARGE;
  for(const k in TEAM_LEAGUE) delete TEAM_LEAGUE[k];
  for(const [lg,ts] of Object.entries(LEAGUES)) ts.forEach(t=>TEAM_LEAGUE[t]=lg);
}

const CAL={ratio:1.008,sd:2.3,n:293};

const MARK_W=[[1],[0.67,0.33],[0.50,0.30,0.20]];

const LONE=0.006;

const TEAM_SHARE=0.30;

const SIG_T=Math.sqrt(TEAM_SHARE), SIG_I=Math.sqrt(1-TEAM_SHARE);

let NEXT_SEASON=false;

function splitCSVLine(l){
  const o=[];let c="",q=false;
  for(let i=0;i<l.length;i++){const ch=l[i];
    if(q){if(ch==='"'){if(l[i+1]==='"'){c+='"';i++;}else q=false;}else c+=ch;}
    else if(ch==='"')q=true;else if(ch===","){o.push(c);c="";}else c+=ch;}
  o.push(c);return o.map(s=>s.trim());
}

function toSeconds(m){
  if(!m)return null;
  const x=String(m).trim().match(/^(\d{1,2}):(\d{1,2})(?:\.(\d+))?$/);
  if(!x)return null;const s=+x[2];if(s>=60)return null;
  return (+x[1])*60+s+(x[3]?+("0."+x[3]):0);
}

function fmt(s){const m=Math.floor(s/60);return m+":"+(s-m*60).toFixed(1).padStart(4,"0");}

function parseCSV(text){
  const lines=text.trim().split(/\r?\n/).filter(l=>l.trim());
  const head=splitCSVLine(lines[0]).map(h=>h.toLowerCase());
  const at=n=>head.indexOf(n);
  const iG=at("gender"),iA=at("athlete"),iT=at("team"),iM=at("mark"),iD=at("dist"),iGr=at("grade"),iC=at("class");
  if(iG<0||iA<0||iT<0||iM<0)throw new Error("Header needs gender, athlete, team and mark.");
  const rows=[];let bad=0;
  for(let i=1;i<lines.length;i++){
    const c=splitCSVLine(lines[i]),raw=toSeconds(c[iM]);
    const g=(c[iG]||"").toUpperCase().charAt(0);
    if(raw===null||(g!=="M"&&g!=="F")){bad++;continue;}
    const dist=iD>-1&&String(c[iD]).indexOf("3")===0?3000:5000;
    rows.push({g,name:c[iA],team:c[iT],dist,sb:raw,grade:iGr>-1?c[iGr]:"",cls:iC>-1?c[iC]:"6A"});
    // duplicate athlete rows are kept, not collapsed — they are the season
  }
  return {rows,bad};
}

function buildModel(g,dist){
  const byTeam=new Map();
  for(const r of DATA){
    if(r.g!==g||r.dist!==dist||r.cls!==CLS)continue;
    if(NEXT_SEASON&&String(r.grade).trim()==="12")continue;   // graduated
    if(!byTeam.has(r.team))byTeam.set(r.team,new Map());
    const t=byTeam.get(r.team);
    if(!t.has(r.name)) t.set(r.name,{name:r.name,grade:r.grade,marks:[]});
    t.get(r.name).marks.push(r.sb);
  }
  for(const t of byTeam.values())
    for(const a of t.values()){
      a.marks.sort((x,y)=>x-y);
      a.marks=a.marks.slice(0,3);       // top three of the season
      a.sbRaw=a.marks[0];               // what they actually ran, for display
      if(a.marks.length===1) a.marks=[a.marks[0]*(1+LONE)];
      a.sb=a.marks[0];
      a.w=MARK_W[a.marks.length-1].slice();
    }
  const teams=[],runners=[],unassigned=[];
  for(const [name,m] of byTeam){
    const lg=TEAM_LEAGUE[name];
    if(!lg){unassigned.push(name);continue;}
    const roster=[...m.values()].sort((a,b)=>a.sb-b.sb).slice(0,7);
    const idx=teams.length;
    if(roster.length<SC){teams.push({name,league:lg,idx,rIdx:[],short:roster.length,avg5:Infinity});continue;}
    const rIdx=roster.map(r=>{runners.push({marks:r.marks,w:r.w,sb:r.sb,t:idx});return runners.length-1;});
    teams.push({name,league:lg,idx,rIdx,short:0,roster,
      avg5:roster.slice(0,SC).reduce((s,r)=>s+r.sb,0)/SC});
  }
  const byLeague={};
  for(const lg of LG) byLeague[lg]=teams.filter(t=>t.league===lg&&!t.short);
  return {teams,runners,byLeague,unassigned};
}

function scoreMeet(list,times,SC,PL){
  SC=SC||5;PL=PL||7;                  // scorers, then how many run before the rest are struck out
  const field=[];
  for(const t of list) for(const i of t.rIdx) field.push({t:times[i],team:t.idx});
  field.sort((a,b)=>a.t-b.t);
  const seen=new Map(),res=new Map();
  for(const t of list) res.set(t.idx,{idx:t.idx,total:0,sixth:null,sumN:0});
  let place=0;
  for(const f of field){
    place++;
    const n=(seen.get(f.team)||0)+1;seen.set(f.team,n);
    if(n>PL)continue;
    const r=res.get(f.team);
    if(n<=SC){r.total+=place;r.sumN+=f.t;}
    else if(n===SC+1)r.sixth=place;   // the first non-scorer breaks a tie
  }
  const out=[...res.values()];
  out.sort((a,b)=>{
    if(a.total!==b.total)return a.total-b.total;
    if(a.sixth===null)return b.sixth===null?0:1;
    if(b.sixth===null)return -1;
    return a.sixth-b.sixth;
  });
  return out;
}

const SK_HI=1.45, SK_LO=0.75;

const SK_MEAN=0.7978845608*(SK_HI-SK_LO)/2;

const SK_SD=Math.sqrt((SK_HI*SK_HI+SK_LO*SK_LO)/2-SK_MEAN*SK_MEAN);

function playDistricts(model,byIdx,times,indOut){
  const {byLeague}=model;
  const autos=[],pool=[],perLeague=[];
  for(const lg of LG){
    const list=byLeague[lg];
    if(!list.length)continue;
    const r=scoreMeet(list,times,SC,PL);
    if(indOut) perLeague.push({list,r});
    for(let p=0;p<r.length;p++){
      const t=byIdx[r[p].idx];
      if(t){t.scoreSum+=r[p].total;t.placeSum+=p+1;t.n++;}   // smooth surrogates
      const A=autoFor(lg);
      if(p<A) autos.push(r[p].idx);
      else if(p<A+2) pool.push({idx:r[p].idx,third:p===A,lg,avg5:r[p].sumN/SC});
    }
  }
  pool.sort((a,b)=>a.avg5-b.avg5);
  const slots=Math.min(AT_LARGE+(autoTotal()-autos.length),pool.length);
  const taken3=new Set(),wilds=[];
  for(const c of pool){
    if(wilds.length>=slots)break;
    if(c.third){taken3.add(c.lg);wilds.push(c.idx);}
    else if(taken3.has(c.lg))wilds.push(c.idx);
  }
  for(const i of autos){byIdx[i].auto++;byIdx[i].qual++;}
  for(const i of wilds){byIdx[i].wild++;byIdx[i].qual++;}
  const field=autos.concat(wilds);
  /* Individual qualifiers: walk the first IND finishers of each district race
     and advance anyone whose team did not make it. Fewer than IND is normal —
     in a strong league the top of the race is all qualifying teams. This runs
     after the at-large places are settled, because those teams count as
     qualified for this purpose. */
  if(indOut){
    const through=new Set(field);
    for(const {list} of perLeague){
      const order=[];
      for(const tm of list) for(const ri of tm.rIdx) order.push({ri,t:times[ri],team:tm.idx});
      order.sort((a,b)=>a.t-b.t);
      const n=Math.min(IND,order.length);
      for(let k=0;k<n;k++) if(!through.has(order[k].team)) indOut.push(order[k].ri);
    }
  }
  return field;
}

function playState(model,byIdx,times,fieldIdx,indIdx,rTally,rTime){
  const {teams}=model;
  /* Every runner on a qualifying team, summed. Divided later by that team's
     ptsN — the count of seasons it actually got to Lane — which is the same
     set of seasons, so the two always agree. No sort, no allocation: this is
     cheap enough to leave switched on for the ordinary odds run. */
  if(rTime) for(const i of fieldIdx) for(const ri of teams[i].rIdx) rTime[ri]+=times[ri];
  const res=scoreMeet(fieldIdx.map(i=>teams[i]),times,SC,PL);
  /* Individual places are scored over everyone on the line — qualifying teams
     plus the individual qualifiers, who run but are struck from team scoring. */
  if(rTally){
    const line=[];
    for(const i of fieldIdx) for(const ri of teams[i].rIdx) line.push(ri);
    if(indIdx) for(const ri of indIdx) line.push(ri);
    line.sort((a,b)=>times[a]-times[b]);
    for(let k=0;k<line.length;k++){
      const r=rTally[line[k]];
      if(!r)continue;
      const place=k+1;
      r.n++; r.placeSum+=place;
      if(place===1)r.win++;
      if(place<=21)r.top21++;      // all-state, three teams of seven
      if(place<r.best)r.best=place;
    }
  }
  for(let p=0;p<res.length;p++){
    const t=byIdx[res[p].idx],place=p+1;
    if(place<=FIELD)t.hist[place]++;
    if(place<=10)t.top10++;
    if(place<=4)t.top4++;
    if(place===1)t.win++;
    t.ptsSum+=res[p].total;t.ptsN++;       // only counts seasons this team actually qualified
  }
}

function skew(){
  const z=gauss();
  return ((z>0?z*SK_HI:z*SK_LO)-SK_MEAN)/SK_SD;
}

let spare=null;

function gauss(){
  if(spare!==null){const v=spare;spare=null;return v;}
  let u,v,s;
  do{u=Math.random()*2-1;v=Math.random()*2-1;s=u*u+v*v;}while(s>=1||s===0);
  const m=Math.sqrt(-2*Math.log(s)/s);
  spare=v*m;return u*m;
}

function pickMark(r){
  if(r.marks.length===1)return r.marks[0];
  let u=Math.random();
  for(let i=0;i<r.w.length;i++){ if(u<r.w[i])return r.marks[i]; u-=r.w[i]; }
  return r.marks[r.marks.length-1];
}

function draw(model,times,sigma,shock){
  const {runners,teams}=model;
  for(let k=0;k<teams.length;k++) shock[k]=gauss()*sigma*SIG_T;
  for(let i=0;i<runners.length;i++){
    const r=runners[i];
    times[i]=pickMark(r)*(1+shock[r.t]+skew()*sigma*SIG_I);
  }
}

function shift(times,adj,tmp){
  if(!adj)return times;
  for(let i=0;i<times.length;i++) tmp[i]=times[i]-adj[i];
  return tmp;
}

function oneSeason(model,worlds,sigma,times,shock,tmp){
  draw(model,times,sigma,shock);
  const inds=worlds.map(w=>w.rt?[]:null);
  const fields=worlds.map((w,i)=>playDistricts(model,w.byIdx,shift(times,w.adj,tmp),inds[i]));
  draw(model,times,sigma,shock);        // state is a fresh race, not a replay
  worlds.forEach((w,i)=>{
    if(fields[i].length>=2) playState(model,w.byIdx,shift(times,w.adj,tmp),fields[i],inds[i],w.rt,w.rtm);
  });
}

function blankTally(model){
  const t=model.teams.filter(x=>!x.short).map(x=>({idx:x.idx,name:x.name,league:x.league,
    avg5:x.avg5,auto:0,wild:0,qual:0,top10:0,top4:0,win:0,scoreSum:0,placeSum:0,n:0,
    ptsSum:0,ptsN:0,                       // state points, averaged over the seasons they got there
    hist:new Array(FIELD+1).fill(0)}));
  const by=[]; for(const x of t) by[x.idx]=x;
  return {list:t,byIdx:by};
}

function runnerTally(model){
  const by=[];
  for(const tm of model.teams){
    if(!tm.roster)continue;
    tm.rIdx.forEach((ri,k)=>{
      by[ri]={ri,name:tm.roster[k].name,team:tm.name,league:tm.league,grade:tm.roster[k].grade,
        sb:tm.roster[k].sbRaw,marks:tm.roster[k].marks.length,
        n:0,placeSum:0,win:0,top21:0,best:1e9};
    });
  }
  return by;
}

let DATA=[];

try{ setClass("6A","M"); }catch(e){}

module.exports = {
  get LEAGUES(){return LEAGUES;}, get LG(){return LG;}, get TEAM_LEAGUE(){return TEAM_LEAGUE;},
  get AUTO(){return AUTO;}, get CLS(){return CLS;}, setCLS(c){ CLS=c; },
  setClass, get AT_LARGE(){return AT_LARGE;}, get FIELD(){return FIELD;},
  get SC(){return SC;}, get PL(){return PL;},
  CAL, MARK_W, TEAM_SHARE, SIG_T, SIG_I,
  parseCSV, toSeconds, fmt, buildModel, scoreMeet, playDistricts, playState,
  gauss, skew, pickMark, draw, shift, oneSeason, blankTally, runnerTally,
  get IND(){return IND;}, setInd(n){ IND=n; },
  get DATA(){return DATA;},
  setDATA(d){ DATA = d; },
  setLeagues(L){
    LEAGUES = L;
    LG = Object.keys(LEAGUES);
    for(const k in TEAM_LEAGUE) delete TEAM_LEAGUE[k];
    for(const [lg,ts] of Object.entries(LEAGUES)) ts.forEach(x=>TEAM_LEAGUE[x]=lg);
    FIELD = autoTotal() + AT_LARGE;
  },
  setBerths(auto, atLarge){
    AUTO = {};
    if (typeof auto === 'number') LG.forEach(l => AUTO[l] = auto); else Object.assign(AUTO, auto);
    AT_LARGE = atLarge; FIELD = autoTotal() + AT_LARGE;
  },
  setDepths(score, place){ SC = score; PL = place || 7; },
};
