// GENERATED by extract_model.js from index.html - do not edit by hand

const LEAGUES={
 "Portland Interscholastic":["Benson Tech","Cleveland","Franklin","Grant","Ida B. Wells","Jefferson-Portland","Lincoln","McDaniel","Roosevelt"],
 "Metro":["Beaverton","Jesuit","Mountainside","Southridge","Sunset","Westview"],
 "Pacific":["Century","Forest Grove","Glencoe","McMinnville","Newberg","Sherwood"],
 "Mt. Hood":["Adrienne Nelson","Barlow","Central Catholic","Clackamas","David Douglas","Gresham","Reynolds"],
 "Three Rivers":["Lake Oswego","Lakeridge","Oregon City","St Mary's Academy","Tigard","Tualatin","West Linn"],
 "Central Valley":["McKay","McNary","North Salem","South Salem","Sprague","West Salem"],
 "Special District 1":["Grants Pass","North Medford","Roseburg","Sheldon","South Eugene","South Medford"]
};

let AUTO_PER=2, AT_LARGE=2;
const LG=Object.keys(LEAGUES);

let FIELD=LG.length*AUTO_PER+AT_LARGE;   // 16

const CAL={ratio:1.008,sd:2.3,n:293};

const MARK_W=[0.25,0.50,0.25];

const TEAM_SHARE=0.30;

const SIG_T=Math.sqrt(TEAM_SHARE), SIG_I=Math.sqrt(1-TEAM_SHARE);

function splitCSVLine(l){
  const o=[];let c="",q=false;
  for(let i=0;i<l.length;i++){const ch=l[i];
    if(q){if(ch==='"'){if(l[i+1]==='"'){c+='"';i++;}else q=false;}else c+=ch;}
    else if(ch==='"')q=true;else if(ch===","){o.push(c);c="";}else c+=ch;}
  o.push(c);return o.map(s=>s.trim());
}

function toSeconds(m){
  if(!m)return null;
  const x=String(m).trim().match(/^(\d{1,2}):(\d{1,2})(?:\.(\d+))?$/);
  if(!x)return null;const s=+x[2];if(s>=60)return null;
  return (+x[1])*60+s+(x[3]?+("0."+x[3]):0);
}

function fmt(s){const m=Math.floor(s/60);return m+":"+(s-m*60).toFixed(1).padStart(4,"0");}

function parseCSV(text){
  const lines=text.trim().split(/\r?\n/).filter(l=>l.trim());
  const head=splitCSVLine(lines[0]).map(h=>h.toLowerCase());
  const at=n=>head.indexOf(n);
  const iG=at("gender"),iA=at("athlete"),iT=at("team"),iM=at("mark"),iD=at("dist"),iGr=at("grade");
  if(iG<0||iA<0||iT<0||iM<0)throw new Error("Header needs gender, athlete, team and mark.");
  const rows=[];let bad=0;
  for(let i=1;i<lines.length;i++){
    const c=splitCSVLine(lines[i]),raw=toSeconds(c[iM]);
    const g=(c[iG]||"").toUpperCase().charAt(0);
    if(raw===null||(g!=="M"&&g!=="F")){bad++;continue;}
    const dist=iD>-1&&String(c[iD]).indexOf("3")===0?3000:5000;
    rows.push({g,name:c[iA],team:c[iT],dist,sb:raw,grade:iGr>-1?c[iGr]:""});
    // duplicate athlete rows are kept, not collapsed — they are the season
  }
  return {rows,bad};
}

function buildModel(g,dist){
  const byTeam=new Map();
  for(const r of DATA){
    if(r.g!==g||r.dist!==dist)continue;
    if(!byTeam.has(r.team))byTeam.set(r.team,new Map());
    const t=byTeam.get(r.team);
    if(!t.has(r.name)) t.set(r.name,{name:r.name,grade:r.grade,marks:[]});
    t.get(r.name).marks.push(r.sb);
  }
  for(const t of byTeam.values())
    for(const a of t.values()){
      a.marks.sort((x,y)=>x-y);
      a.marks=a.marks.slice(0,3);       // top three of the season
      a.sb=a.marks[0];
      a.w=MARK_W.slice(0,a.marks.length);
      const s=a.w.reduce((p,q)=>p+q,0);
      a.w=a.w.map(v=>v/s);              // renormalise when fewer than three
    }
  const teams=[],runners=[],unassigned=[];
  for(const [name,m] of byTeam){
    const lg=TEAM_LEAGUE[name];
    if(!lg){unassigned.push(name);continue;}
    const roster=[...m.values()].sort((a,b)=>a.sb-b.sb).slice(0,7);
    const idx=teams.length;
    if(roster.length<5){teams.push({name,league:lg,idx,rIdx:[],short:roster.length,avg5:Infinity});continue;}
    const rIdx=roster.map(r=>{runners.push({marks:r.marks,w:r.w,sb:r.sb,t:idx});return runners.length-1;});
    teams.push({name,league:lg,idx,rIdx,short:0,roster,
      avg5:roster.slice(0,5).reduce((s,r)=>s+r.sb,0)/5});
  }
  const byLeague={};
  for(const lg of LG) byLeague[lg]=teams.filter(t=>t.league===lg&&!t.short);
  return {teams,runners,byLeague,unassigned};
}

function scoreMeet(list,times){
  const field=[];
  for(const t of list) for(const i of t.rIdx) field.push({t:times[i],team:t.idx});
  field.sort((a,b)=>a.t-b.t);
  const seen=new Map(),res=new Map();
  for(const t of list) res.set(t.idx,{idx:t.idx,total:0,sixth:null,sum5:0});
  let place=0;
  for(const f of field){
    place++;
    const n=(seen.get(f.team)||0)+1;seen.set(f.team,n);
    if(n>7)continue;
    const r=res.get(f.team);
    if(n<=5){r.total+=place;r.sum5+=f.t;}
    else if(n===6)r.sixth=place;
  }
  const out=[...res.values()];
  out.sort((a,b)=>{
    if(a.total!==b.total)return a.total-b.total;
    if(a.sixth===null)return b.sixth===null?0:1;
    if(b.sixth===null)return -1;
    return a.sixth-b.sixth;
  });
  return out;
}

const SK_HI=1.45, SK_LO=0.75;

const SK_MEAN=0.7978845608*(SK_HI-SK_LO)/2;

const SK_SD=Math.sqrt((SK_HI*SK_HI+SK_LO*SK_LO)/2-SK_MEAN*SK_MEAN);

function playDistricts(model,byIdx,times){
  const {byLeague}=model;
  const autos=[],pool=[];
  for(const lg of LG){
    const list=byLeague[lg];
    if(!list.length)continue;
    const r=scoreMeet(list,times);
    for(let p=0;p<r.length;p++){
      const t=byIdx[r[p].idx];
      if(t){t.scoreSum+=r[p].total;t.placeSum+=p+1;t.n++;}   // smooth surrogates
      if(p<AUTO_PER) autos.push(r[p].idx);
      else if(p<AUTO_PER+2) pool.push({idx:r[p].idx,third:p===AUTO_PER,lg,avg5:r[p].sum5/5});
    }
  }
  pool.sort((a,b)=>a.avg5-b.avg5);
  const slots=Math.min(AT_LARGE+(LG.length*AUTO_PER-autos.length),pool.length);
  const taken3=new Set(),wilds=[];
  for(const c of pool){
    if(wilds.length>=slots)break;
    if(c.third){taken3.add(c.lg);wilds.push(c.idx);}
    else if(taken3.has(c.lg))wilds.push(c.idx);
  }
  for(const i of autos){byIdx[i].auto++;byIdx[i].qual++;}
  for(const i of wilds){byIdx[i].wild++;byIdx[i].qual++;}
  return autos.concat(wilds);
}

function playState(model,byIdx,times,fieldIdx){
  const {teams}=model;
  const res=scoreMeet(fieldIdx.map(i=>teams[i]),times);
  for(let p=0;p<res.length;p++){
    const t=byIdx[res[p].idx],place=p+1;
    if(place<=FIELD)t.hist[place]++;
    if(place<=10)t.top10++;
    if(place<=4)t.top4++;
    if(place===1)t.win++;
  }
}

function skew(){
  const z=gauss();
  return ((z>0?z*SK_HI:z*SK_LO)-SK_MEAN)/SK_SD;
}

let spare=null;

function gauss(){
  if(spare!==null){const v=spare;spare=null;return v;}
  let u,v,s;
  do{u=Math.random()*2-1;v=Math.random()*2-1;s=u*u+v*v;}while(s>=1||s===0);
  const m=Math.sqrt(-2*Math.log(s)/s);
  spare=v*m;return u*m;
}

function pickMark(r){
  if(r.marks.length===1)return r.marks[0];
  let u=Math.random();
  for(let i=0;i<r.w.length;i++){ if(u<r.w[i])return r.marks[i]; u-=r.w[i]; }
  return r.marks[r.marks.length-1];
}

function draw(model,times,sigma,shock){
  const {runners,teams}=model;
  for(let k=0;k<teams.length;k++) shock[k]=gauss()*sigma*SIG_T;
  for(let i=0;i<runners.length;i++){
    const r=runners[i];
    times[i]=pickMark(r)*(1+shock[r.t]+skew()*sigma*SIG_I);
  }
}

function shift(times,adj,tmp){
  if(!adj)return times;
  for(let i=0;i<times.length;i++) tmp[i]=times[i]-adj[i];
  return tmp;
}

function oneSeason(model,worlds,sigma,times,shock,tmp){
  draw(model,times,sigma,shock);
  const fields=worlds.map(w=>playDistricts(model,w.byIdx,shift(times,w.adj,tmp)));
  draw(model,times,sigma,shock);        // state is a fresh race, not a replay
  worlds.forEach((w,i)=>{
    if(fields[i].length>=2) playState(model,w.byIdx,shift(times,w.adj,tmp),fields[i]);
  });
}

function blankTally(model){
  const t=model.teams.filter(x=>!x.short).map(x=>({idx:x.idx,name:x.name,league:x.league,
    avg5:x.avg5,auto:0,wild:0,qual:0,top10:0,top4:0,win:0,scoreSum:0,placeSum:0,n:0,
    hist:new Array(FIELD+1).fill(0)}));
  const by=[]; for(const x of t) by[x.idx]=x;
  return {list:t,byIdx:by};
}

const TEAM_LEAGUE={};
function reindexLeagues(){
  for(const k in TEAM_LEAGUE) delete TEAM_LEAGUE[k];
  for(const [lg,ts] of Object.entries(LEAGUES)) ts.forEach(t=>TEAM_LEAGUE[t]=lg);
}
reindexLeagues();

let DATA=[];

module.exports = {
  get LEAGUES(){return LEAGUES;}, get LG(){return LG;}, get TEAM_LEAGUE(){return TEAM_LEAGUE;},
  get AUTO_PER(){return AUTO_PER;}, get AT_LARGE(){return AT_LARGE;}, get FIELD(){return FIELD;},
  CAL, MARK_W, TEAM_SHARE, SIG_T, SIG_I,
  parseCSV, toSeconds, fmt, buildModel, scoreMeet, playDistricts, playState,
  gauss, skew, pickMark, draw, shift, oneSeason, blankTally,
  get DATA(){return DATA;},
  setDATA(d){ DATA = d; },
  setLeagues(L){
    for(const k in LEAGUES) delete LEAGUES[k];
    Object.assign(LEAGUES, L);
    LG.length = 0; LG.push(...Object.keys(LEAGUES));
    reindexLeagues();
    FIELD = LG.length*AUTO_PER + AT_LARGE;
  },
  setBerths(auto, atLarge){ AUTO_PER = auto; AT_LARGE = atLarge; FIELD = LG.length*AUTO_PER + AT_LARGE; },
};
